DROP TABLE IF EXISTS invoice_qr_token;
DROP TABLE IF EXISTS finance_session_token;
DROP TABLE IF EXISTS invoice_import_row_error;
DROP TABLE IF EXISTS invoice_import_task;
DROP TABLE IF EXISTS invoice_operation_log;
DROP TABLE IF EXISTS invoice_title_version;
DROP TABLE IF EXISTS subject_department_employee_exclusion;
DROP TABLE IF EXISTS subject_permission;
DROP TABLE IF EXISTS ding_employee_department;
DROP TABLE IF EXISTS ding_directory_sync_log;
DROP TABLE IF EXISTS ding_employee;
DROP TABLE IF EXISTS ding_department;
DROP TABLE IF EXISTS invoice_title_subject;
DROP TABLE IF EXISTS invoice_subject;
DROP TABLE IF EXISTS invoice_title;
DROP TABLE IF EXISTS finance_user;

CREATE TABLE finance_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    role_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    password_changed_at TIMESTAMP,
    last_login_at TIMESTAMP,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE finance_session_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash CHAR(64) NOT NULL UNIQUE,
    finance_user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_finance_session_account FOREIGN KEY (finance_user_id) REFERENCES finance_user (id) ON DELETE CASCADE
);

CREATE TABLE invoice_title (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR(200) NOT NULL,
    taxpayer_id VARCHAR(32) NOT NULL,
    registered_address VARCHAR(500),
    phone VARCHAR(50),
    bank_name VARCHAR(200),
    bank_account VARCHAR(64),
    status VARCHAR(20) NOT NULL,
    current_published_version_id BIGINT,
    subject_names VARCHAR(500),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(100),
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE invoice_title_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    status VARCHAR(20) NOT NULL,
    change_type VARCHAR(30) NOT NULL DEFAULT 'EDIT',
    change_summary VARCHAR(500),
    company_name VARCHAR(200) NOT NULL,
    taxpayer_id VARCHAR(32) NOT NULL,
    registered_address VARCHAR(500),
    phone VARCHAR(50),
    bank_name VARCHAR(200),
    bank_account VARCHAR(64),
    subject_ids_json VARCHAR(2000),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE invoice_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name VARCHAR(100) NOT NULL,
    subject_code VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    all_employee_visible TINYINT NOT NULL DEFAULT 0,
    sort_no INT NOT NULL DEFAULT 0,
    created_by VARCHAR(100) NOT NULL DEFAULT 'test',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'test',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE invoice_title_subject (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    created_by VARCHAR(100) NOT NULL DEFAULT 'test',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_invoice_title_subject_title UNIQUE (title_id),
    CONSTRAINT uk_invoice_title_subject_subject UNIQUE (subject_id)
);

CREATE TABLE subject_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    target_type VARCHAR(20) NOT NULL,
    target_corp_code VARCHAR(50) NOT NULL DEFAULT 'default',
    target_id VARCHAR(100) NOT NULL,
    target_name VARCHAR(200) NOT NULL,
    permission_effect VARCHAR(20) NOT NULL DEFAULT 'ALLOW',
    include_child_departments TINYINT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    created_by VARCHAR(100) NOT NULL DEFAULT 'test',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL DEFAULT 'test',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE ding_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code VARCHAR(50) NOT NULL DEFAULT 'default',
    corp_name VARCHAR(200) NOT NULL DEFAULT '默认钉钉企业',
    corp_id VARCHAR(100),
    ding_department_id VARCHAR(100) NOT NULL,
    department_name VARCHAR(200) NOT NULL,
    parent_department_id VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
    sort_no INT NOT NULL DEFAULT 0,
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (corp_code, ding_department_id)
);

CREATE TABLE ding_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corp_code VARCHAR(50) NOT NULL DEFAULT 'default',
    corp_name VARCHAR(200) NOT NULL DEFAULT '默认钉钉企业',
    corp_id VARCHAR(100),
    ding_user_id VARCHAR(100) NOT NULL,
    union_id VARCHAR(100),
    employee_no VARCHAR(50) NOT NULL,
    employee_name VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    department_name VARCHAR(200) NOT NULL,
    mobile VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    last_synced_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (corp_code, ding_user_id),
    UNIQUE (corp_code, employee_no)
);

CREATE TABLE ding_employee_department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    is_primary TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, department_id)
);

CREATE TABLE subject_department_employee_exclusion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_subject_department_employee_exclusion UNIQUE (subject_id, department_id, employee_id),
    CONSTRAINT fk_subject_department_employee_exclusion_subject FOREIGN KEY (subject_id) REFERENCES invoice_subject (id),
    CONSTRAINT fk_subject_department_employee_exclusion_department FOREIGN KEY (department_id) REFERENCES ding_department (id),
    CONSTRAINT fk_subject_department_employee_exclusion_employee FOREIGN KEY (employee_id) REFERENCES ding_employee (id)
);

CREATE TABLE ding_directory_sync_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    department_count INT NOT NULL DEFAULT 0,
    employee_count INT NOT NULL DEFAULT 0,
    operator_name VARCHAR(100) NOT NULL,
    error_message VARCHAR(1000),
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP
);

CREATE TABLE invoice_qr_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL UNIQUE,
    title_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    employee_id BIGINT,
    ding_user_id VARCHAR(100),
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE invoice_operation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_type VARCHAR(30) NOT NULL,
    operation_type VARCHAR(30) NOT NULL,
    business_id VARCHAR(64) NOT NULL,
    business_name VARCHAR(200),
    detail_json VARCHAR(2000),
    result VARCHAR(20) NOT NULL,
    operator_user_id VARCHAR(100) NOT NULL,
    operator_name VARCHAR(100) NOT NULL,
    client_ip VARCHAR(64),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE invoice_import_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_no VARCHAR(40) NOT NULL UNIQUE,
    original_file_name VARCHAR(255) NOT NULL,
    storage_provider VARCHAR(20) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    failure_count INT NOT NULL DEFAULT 0,
    error_file_key VARCHAR(500),
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE invoice_import_row_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    row_no INT NOT NULL,
    taxpayer_id VARCHAR(32),
    error_code VARCHAR(50) NOT NULL,
    error_message VARCHAR(500) NOT NULL,
    raw_data_json VARCHAR(4000),
    created_at TIMESTAMP NOT NULL
);
