spring:
  config:
    import: optional:nacos:invoice-title-service.yml
  cloud:
    discovery:
      enabled: true
    nacos:
      server-addr: 127.0.0.1:28848
      config:
        enabled: true
      discovery:
        enabled: true
        server-addr: 127.0.0.1:28848
  flyway:
    locations: classpath:db/migration,classpath:db/local
